### PR TITLE
ci: add e2e testing in chrome, firefox and ie browsers

### PR DESCRIPTION
**Pull request by miherlosev**

### CODE REVIEW

**Comment by miherlosev** [comment]
@GitScrum 
I will run e2e tests only on `appveyor`.
It is Ok?

**Comment by Scrum** [comment]
@miherlosev ok, how can I make `travis` ?

**Comment by miherlosev** [comment]
Review, please

**Review by Scrum — APPROVED** [review]

**Comment by Scrum** [comment]
@miherlosev how can I make `travis` ?

**Comment by miherlosev** [comment]
> how can I make travis ?

What do you mean?

**Comment by Scrum** [comment]
how can I do the same under `travis` ?

**Comment by miherlosev** [comment]
Yes. 
On `travis ci`  you can easyly setup e2e on Chrome and Firefox browsers.
So, I can do this in a separate pull request at the end of week

**Comment by Scrum** [comment]
> at the end of week

👍

**Pull request merged**
